### PR TITLE
Add missing slots

### PR DESCRIPTION
**Pull request by q0w**
Checked by slotscheck
# Checklist

- [ ] Changes finished
- [ ] Tests added (if applicable)
- [ ] Documentation adjusted (if applicable)
- [ ] Added entry to changelog (`HISTORY.rst`)
- [ ] `tox` runs OK
- [ ] Build runs OK

### CODE REVIEW

**Comment by ariebovenberg** [comment]
@q0w ahahahaa WOW 😅 

thanks 🙏 

Let's add this wonderful tool to the CI as well ;)

**Comment by ariebovenberg** [comment]
Looks like there are more to fix?

```
ERROR: 'snug.clients:_SocketAdaptor' has no slots but superclass does.
ERROR: 'snug.pagination:paginated' has slots but superclass does not.
ERROR: 'snug.query:Query' has no slots but superclass does.
ERROR: 'snug.query:related' has no slots but superclass does.
Oh no, found some problems!
Scanned 6 module(s), 12 class(es).
```

**Comment by ariebovenberg** [comment]
Looks like `quiz` also has some to be fixed: 

```
ERROR: 'quiz.execution:ErrorResponse' has slots but superclass does not.
ERROR: 'quiz.execution:HTTPError' has slots but superclass does not.
ERROR: 'quiz.types:InvalidArgumentType' has slots but superclass does not.
ERROR: 'quiz.types:MissingArgument' has slots but superclass does not.
ERROR: 'quiz.types:NoSuchArgument' has slots but superclass does not.
ERROR: 'quiz.types:NoSuchField' has slots but superclass does not.
ERROR: 'quiz.types:SelectionError' has slots but superclass does not.
ERROR: 'quiz.types:SelectionsNotSupported' has slots but superclass does not.
```

**Comment by ariebovenberg** [comment]
Although those are exception subclasses -- something to solve in a different way...

**Comment by q0w** [comment]
@ariebovenberg now slotscheck cant be added in tox, because poetry does not install project itself, so 
```python
try:
    __version__ = __import__("importlib.metadata").metadata.version(__name__)
except ModuleNotFoundError:  # pragma: no cover
    __version__ = __import__("importlib_metadata").version(__name__)
```
causes errors when running `python -m slotscheck -m src.snug`

**Comment by ariebovenberg** [comment]
Hmmm, yes...`src` should never need to be included in the module name. Let me try and see.

**Pull request merged**
