### PR TITLE
Add `httpx`

### PR DESCRIPTION
**Pull request by q0w**

### CODE REVIEW

**Comment by ariebovenberg** [comment]
Nice! 🥇 I see you already fixed the lint issue 👀 

You'll also need to add `httpx =  {version = "...", optional = true}` to `[tool.poetry.dependencies]` section of `pyproject.toml`

**Comment by q0w** [comment]
`Anyio` requires python [>=3.6.2](https://github.com/agronholm/anyio/blob/master/setup.cfg)

**Comment by ariebovenberg** [comment]
Indeed. The latest `black` as well. Feel free to up the minimum python version in `pyproject.toml` to `3.6.2` 👍

**Comment by q0w** [comment]
Shoud tox also run tests for extras? Seems tox ignores extra deps and skips their tests

**Comment by ariebovenberg** [comment]
The base `[testenv]` does include them. You'll need to add `httpx` to it indeed. Good catch!

**Comment by q0w** [comment]
Done

**Comment by ariebovenberg** [comment]
👏 excellent. I'll merge and create a release.

**Comment by ariebovenberg** [comment]
@q0w release created. version 2.3.0 is now out with your changes.

**Pull request merged**
